# fly.toml app configuration file generated for nyatta-staging on 2023-07-07T02:59:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nyatta-staging"
primary_region = "jnb"

[http_service]
  internal_port = 4000
  force_https = true
  min_machines_running = 0
  processes = ["app"]
