# fly.toml file generated for nyatta on 2023-04-13T20:03:46+03:00

app = "nyatta-staging"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "jnb"
processes = []

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
