version: 2.1

# Define jobs to be invoked later in a workflow
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    working_directory: ~/repo
    # Specify execution environment
    docker:
      - image: cimg/go:1.15.10
    # Add steps to job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      # Restore project dependencies from cache
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      # Install project dependencies
      - run:
          name: Install Dependencies
          command: go mod download
      # Save project dependencies in cache
      - save_cache:
          key: go-mod-v4-{{ "go.sum" }}
          paths:
          - "go/pkg/mod"
      # Run project test files
      #- run:
      #    name: Run tests
      #    command: go test -v ./...
# Invoke workflow
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
