name: Go

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
          # Cache dependencies
          cache: true
      # Display go version
      - name: Display Go version
        run: go version
      # Install dependencies
      - name: Install dependencies
        run: go get .
