name: test

on:
  push:
    branches: "*"

jobs:

  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
      
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
        
    # Setup go
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Go version
      run: go version
