name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: demo1234
          POSTGRES_DB: nyatta
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_ready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          # Cache dependencies
          cache: true
      # Display go version
      - name: Display Go version
        run: go version
      # Install dependencies
      - name: Install dependencies
        run: go get .
