name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: demo1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          # Cache dependencies
          cache: true
      # Display go version
      - name: Display Go version
        run: go version
      # Install dependencies
      - name: Install dependencies
        run: go get .
      # Test
      - name: Test
        env:
          # DB - postgresql
          DBDRIVER: postgres
          DBHOST: postgres
          DBPORT: 5432
          DBNAME: nyatta-test
          DBUSER: postgres
          DBPASS: demo1234
          DBSSLMODE: disable
          # Server
          PORT: 4000
          SERVERPORT: 4000
          # Server env
          SERVERENV: test
          # Jwt
          JWTEXPIRE: 3600s
          JWTSECRET: t95xjRO2nWOnfj4HdxgrXKwHSzOl6DOmgyA919pk2PUofbBrsgQRwvptzcbVmDP3 # generated by - (pwgen -s -1 64)
