name: Test
on:
  push:
    branches: "*"
jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        # Provide credentials for postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3
    # Setup go
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19
    - name: Test
      # Env vars
      env:
        # DB
        DBDRIVER: "${{ secrets.DBDRIVER }}"
        DBHOST: localhost
        DBPORT: 5432
        DBNAME: postgres
        DBUSER: postgres
        DBPASS: postgres
        # Server
        SERVERENV: "${{ secrets.SERVERENV }}"
        SERVERPORT: "${{ secrets.SERVERPORT }}"
        # Jwt
        JWTEXPIRE: "${{ secrets.JWTEXPIRE }}"
        JWTSECRET: "${{ secrets.JWTSECRET }}"
      run: make test
